name: Manual Release Version

on: [workflow_dispatch]


jobs:
  release-version:
    name: Manual Release Version
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Verify current inputs godot_version
      run: |
        #BRANCH_NAME=${{ github.ref_name }}

    - name: Check branch
      run: |
        if [ "${{ github.ref_name }}" != "master" ]; then
          echo "This workflow only runs on the master branch."
          exit 1
        fi

    - name: Get version from plugin.cfg
      run: |
        VERSION=$(grep "version=" addons/admob/plugin.cfg | cut -d'"' -f2)
        echo "PLUGIN_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{env.PLUGIN_VERSION}}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.8'

    - name: Install requests
      run: pip install requests
      
    - name: Upload new version to Godot Asset Library
      env:
        USERNAME: ${{ secrets.ASSET_LIBRARY_USERNAME }}
        PASSWORD: ${{ secrets.ASSET_LIBRARY_PASSWORD }}
        VERSION: ${{env.PLUGIN_VERSION}}
        COMMIT_HASH: ${{ github.sha }}
      run: |
        python3 static/workflow_files/push.py

  deploy-docs:
    needs: release-version
    uses: ./.github/workflows/docs.yml